### ISSUE TITLE
Code release timeline? 

### ISSUE THREAD

**Issue by pjtunney** [ygtxr1997/CelebBasis#1]
Thanks for the really cool work, excited to try it.

Any timeline for code release?

Feel fee to close if you feel not relevant.

**Comment by ygtxr1997** [comment]
Thanks for your attention!
We plan to release the code in 1~2 weeks.

**Comment by justindujardin** [comment]
Thanks for the code release!  Your approach is very cool. I've tested it and confirmed that it works, though the results on my own images aren't quite as nice as in your paper.
