### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by euminds** [ygtxr1997/CelebBasis#12]
Getting this error:
(celebbasis) user@amax:/data_heat/rjt_project/CelebBasis$ bash ./01_start_train.sh ./weights/sd-v1-4-full-ema.ckpt 
Global seed set to 23
Running on GPUs 0,
Loading model from ./weights/sd-v1-4-full-ema.ckpt
Traceback (most recent call last):
  File "main_id_embed.py", line 621, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main_id_embed.py", line 32, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/user/miniconda3/envs/celebbasis/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/user/miniconda3/envs/celebbasis/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_id_embed.py", line 833, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

env:
I have configured the environment by following these steps:

I used the command conda env create -f environment.yaml to create the environment based on the specifications provided in the environment.yaml file.

Then, I activated the environment using the command conda activate celebbasis. By changing the environment name to "celebbasis," I ensured that I am working within this specific environment.

Regarding the dependencies mentioned:

The line # - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers refers to the "taming-transformers" library. Due to network issues, I independently installed this dependency using the command pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers.

Similarly, the line # - -e git+https://github.com/openai/CLIP.git@main#egg=clip refers to the "CLIP" library. You installed this dependency separately as well, using the command pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip.

Next , 
About Face Alignment
I align the images in Img, like id0(1).jpg,...,id0(10).jpg. I think this is a minor issue.
Then, I run bash ./01_start_train.sh ./weights/sd-v1-4-full-ema.ckpt and meet the top error

Thanks

**Comment by euminds** [comment]
I have resolved this issue， thanks

**Comment by JarrentWu1031** [comment]
> I have resolved this issue， thanks

Hello, may I ask how did you solve this problem?
