### ISSUE TITLE
confusing about the shape of B?

### ISSUE THREAD

**Issue by CuddleSabe** [ygtxr1997/CelebBasis#17]
B = PCA(Ck, p) = R^{mxp}， but the shape of C_bar is R^d, how to compute it?

<img width="244" alt="截屏2023-11-06 19 28 38" src="https://github.com/ygtxr1997/CelebBasis/assets/61224076/b8fbeadd-1f38-4752-997b-ac475af2c975">

**Comment by CuddleSabe** [comment]
![截屏2023-11-06 19 39 10](https://github.com/ygtxr1997/CelebBasis/assets/61224076/2c3c7003-9240-4346-bcb1-6e0ef98ab0f1)
maybe the paper is wrong.... paper say u use the pca on the second dim, but the code is the first dim!

**Comment by ygtxr1997** [comment]
PCA aims to reduce the dimension of a matrix in shape $m\times n$ into $m\times k$ in the 2nd dimension.
However, in 3DMM and our method, we DO NOT directly use this reduced $m\times k$ matrix, but the itermediate result P in the shape of $k \times m$. Here P can be considered as a **mapping matrix**, that is, the relationship between the unreduced dimensions (768) and the reduced dimensions (maybe 512). You may refer to the 3DMM paper to find out more details. Our paper's B is mainly based on the P mapping matrix but not the reduced input embeddings.

**Comment by CuddleSabe** [comment]
> PCA aims to reduce the dimension of a matrix in shape 
> m
> ×
> n
>  into 
> m
> ×
> k
>  in the 2nd dimension.
> However, in 3DMM and our method, we DO NOT directly use this reduced 
> m
> ×
> k
>  matrix, but the itermediate result P in the shape of 
> k
> ×
> m
> . Here P can be considered as a **mapping matrix**, that is, the relationship between the unreduced dimensions (768) and the reduced dimensions (maybe 512). You may refer to the 3DMM paper to find out more details. Our paper's B is mainly based on the P mapping matrix but not the reduced input embeddings.

thanks! my fault ;)

**Comment by ygtxr1997** [comment]
🤗
