### ISSUE TITLE
00_align_face.sh errors out due to hardcoded paths and missing weights/.pth(s)

### ISSUE THREAD

**Issue by mjdi** [ygtxr1997/CelebBasis#2]
I get the following error running `bash 00_align_face.sh <...>/ori <...>/ffhq`

```
(sd) wsl@MJDFW:~/repos/CelebBasis$ bash 00_align_face.sh /home/wsl/repos/CelebBasis/my_imgs/ori/ /home/wsl/repos/CelebBasis/my_imgs/ffhq/
running build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
Traceback (most recent call last):
  File "./evaluation/face_align/PIPNet/start_align.py", line 85, in <module>
    main(opt)
  File "./evaluation/face_align/PIPNet/start_align.py", line 35, in main
    folder_dataset = FolderAlignCrop(
  File "/home/wsl/repos/CelebBasis/evaluation/face_align/PIPNet/alignment/dataloader.py", line 40, in __init__
    self.net, self.detector = get_lmk_model()
  File "/home/wsl/repos/CelebBasis/evaluation/face_align/PIPNet/lib/tools.py", line 62, in get_lmk_model
    state_dict = torch.load(weight_file, map_location=device)
  File "/home/wsl/anaconda3/envs/sd/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/wsl/anaconda3/envs/sd/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/wsl/anaconda3/envs/sd/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/gavin/code/FaceSwapping/inference/PIPNet/weights/epoch59.pth'
```

due to the hardcoded paths in the get_lmk_model() function in `evaluation/face_align/PIPNet/lib/tools.py` as seen here

![wsl@MJDFW_~reposCelebBasis_10_56_01](https://github.com/ygtxr1997/CelebBasis/assets/24360385/9d91e0d4-809b-4397-b470-4f9673cf9acb)

As we can see here, there should be PIPNet weights (and epoch59.pth ?) which need to be downloaded (and instructions for doing so in the README.md)

![wsl@MJDFW_~reposCelebBasisevaluationface_alignPIPN_11_04_53](https://github.com/ygtxr1997/CelebBasis/assets/24360385/04a7213e-3d88-45dc-a63a-e8e64e0783d5)

Please advise, thanks!

**Comment by justindujardin** [comment]
You need to add the weights files from your screenshot somewhere and fix the paths:
 - "epoch59.pth" https://drive.google.com/file/d/1Jb97z5Z5ca61-6W2RDOK0e2w_RlbeWgS/view?usp=drive_link
 - "FaceBoxesV2.pth" https://github.com/jhb86253817/PIPNet/blob/master/FaceBoxesV2/weights/FaceBoxesV2.pth

**Comment by ygtxr1997** [comment]
We use [PIPNet](https://github.com/jhb86253817/PIPNet) to align and crop the face, but missed their weight files.
You may visit [PIPNet repo](https://github.com/jhb86253817/PIPNet) to download the missing weight files or using the [files](https://github.com/ygtxr1997/CelebBasis/issues/2#issuecomment-1607775140) provided by @justindujardin .
These files can also be downloaded from our [Baidu Yun Drive](https://pan.baidu.com/s/1Cgw0i723SyeLo5lbJu-b0Q) with extracting code `ygss`.
We'll fix the `hardcoded file paths` ASAP!

**Comment by aiXander** [comment]
Just updating the paths to relative paths (after putting the weight files there) works:
```
    weight_file = 'evaluation/face_align/PIPNet/weights/epoch59.pth'
    state_dict = torch.load(weight_file, map_location=device)
    net.load_state_dict(state_dict)

    detector = FaceBoxesDetector(
        "FaceBoxes",
        "evaluation/face_align/PIPNet/weights/FaceBoxesV2.pth",
        use_gpu=True,
        device="cuda:0",
    )
```

**Comment by aiXander** [comment]
This entire section of code is also full of hardcoded paths:
https://github.com/ygtxr1997/CelebBasis/blob/main/scripts/stable_txt2img.py#L272

**Comment by ygtxr1997** [comment]
> Just updating the paths to relative paths (after putting the weight files there) works:
> 
> evaluation/face_align/PIPNet/lib/tools.py line 60:
> 
> ```
>     weight_file = 'evaluation/face_align/PIPNet/weights/epoch59.pth'
>     state_dict = torch.load(weight_file, map_location=device)
>     net.load_state_dict(state_dict)
> 
>     detector = FaceBoxesDetector(
>         "FaceBoxes",
>         "evaluation/face_align/PIPNet/weights/FaceBoxesV2.pth",
>         use_gpu=True,
>         device="cuda:0",
>     )
> ```
1. Code updated, [https://github.com/ygtxr1997/CelebBasis/commit/82fdc0eb1b5b93bff5704ba14fda04420eaa19e0](https://github.com/ygtxr1997/CelebBasis/commit/82fdc0eb1b5b93bff5704ba14fda04420eaa19e0).

> This entire section of code is also full of hardcoded paths: https://github.com/ygtxr1997/CelebBasis/blob/main/scripts/stable_txt2img.py#L272
2. For `stable_txt2img.py#L272`, these hardcoded paths are not used under the default setting. We consider removing these codes or adding the relevant testing options.
