### ISSUE TITLE
Colab link?

### ISSUE THREAD

**Issue by adhikjoshi** [ygtxr1997/CelebBasis#3]
Do you have a google colab for this?

**Comment by ygtxr1997** [comment]
Thanks for your suggestion, we added `colab project` in the TODO list.

**Comment by ygtxr1997** [comment]
Colab link now opened. But limited by 16GB GPU memory, I have to lower the training batch size, leading to little worse performance. Does anyone know how to enlarge the GPU memory on Colab?

**Comment by wouterverweirder** [comment]
The A100 machines on Colab have higher RAM, but you might need a Colab Pro account to access those.
