### ISSUE TITLE
very slow start_align.py unless change is made to DataLoader instance

### ISSUE THREAD

**Issue by mjdi** [ygtxr1997/CelebBasis#4]
I needed to make a change in  `/evaluation/face_align/PIPNet/start_align.py` on line 40 during the DataLoader object instance from `num_workers=1` to `num_workers=0`, or else the tqdm was just hanging indefinitely, as seen in this forum post talking about num_workers>0 https://discuss.pytorch.org/t/dataloader-slower-with-num-workers-0/100970 (up to 50 times slower)

Perhaps it depends on system configuration, but this is what I needed to do to get it to run instantly, and not hang indefinitely, hope it helps others out!

**Comment by justindujardin** [comment]
I had the same issue and made the same edit

**Comment by ygtxr1997** [comment]
Code updated, [https://github.com/ygtxr1997/CelebBasis/commit/c2819fc26c8c0233905cb3713dd05592d595bf1f](https://github.com/ygtxr1997/CelebBasis/commit/c2819fc26c8c0233905cb3713dd05592d595bf1f).
