### ISSUE TITLE
no .pickle file for /infer_images folder?

### ISSUE THREAD

**Issue by mjdi** [ygtxr1997/CelebBasis#5]
I'm very confused, I see there are a lot of images in the /infer_images folder, including /reg or regularization images, and the stylegan3 examples under /ffhq. 
![infer_images_00_36_16](https://github.com/ygtxr1997/CelebBasis/assets/24360385/734791cd-296e-4b0b-8edf-01c8d054416b)

However, the pickle file I made in step 00 (face alignment) doesn't generate or include reg images, so when it's unpickled it just contains my (single) aligned cropped photo (I used the pretty print package to display the unpickled dictionary)
![00_39_36](https://github.com/ygtxr1997/CelebBasis/assets/24360385/9e7181c5-c3f6-4f52-9eeb-0024db1cca4a)
and gives me an error message about missing regularization images.

the pickle_path seems to default to another hardcoded location from a fellow named gavin, and this path includes stylegan3 in the name, hence my confusion
![face_id py_-_CelebBasis_-_Visual_Studio_Code_01_08_17](https://github.com/ygtxr1997/CelebBasis/assets/24360385/13df0b17-25fe-444f-934a-40e2409a592b)

Please advise!

**Comment by mjdi** [comment]
Oh! no need to worry about the .pickle file for /infer_images or stylegan3 now! ^_^ 

Ya, so I don't know exactly which of these changes I made fixed the issue, and I'm too laxy to check, but I guess these show what I did to get it to work. I had the right target in the .yaml file actually, and since FaceIdDatasetOneShot inherits from FaceIdDatasetStyleGAN3
![face_id py_-_CelebBasis_-_Visual_Studio_Code_11_50_38](https://github.com/ygtxr1997/CelebBasis/assets/24360385/aee81db6-4d67-41dc-9e97-a0ca2227d46f)
I still needed to adjust the latter child class.

I guess there is only one id because I'm just training myself?
![wsl@MJDFW_~reposCelebBasis_12_21_02](https://github.com/ygtxr1997/CelebBasis/assets/24360385/2e7f26db-be5c-4e2e-a25a-64edf20eb7ff)

But In the paper it's possible to train multiple people and have them appear separate/distinct in a generated photo (which most other AIGC methods can't do btw! so that's awesome) 
![Inserting_Anybody_in_Diffusion_Models_via_Celeb_Ba_12_26_39](https://github.com/ygtxr1997/CelebBasis/assets/24360385/00c6c116-8223-43b8-81bb-4c7615d01911)

The, the other change I had to make was here I think? maybe not if the defaults are overwritten anyway, I'm not sure
![face_id py_-_CelebBasis_-_Visual_Studio_Code_12_19_30](https://github.com/ygtxr1997/CelebBasis/assets/24360385/54914e77-5fb7-4907-a954-6ad130630f65)

I just added some print statements so I could better understand the logical flow of the _load_from_pickle() method
![face_id py_-_CelebBasis_-_Visual_Studio_Code_12_20_49](https://github.com/ygtxr1997/CelebBasis/assets/24360385/ce06f8cf-03c6-4eef-8765-6b5aad08ca97)

and here you can see the print statements in the output 
![wsl@MJDFW_~reposCelebBasis_12_19_00](https://github.com/ygtxr1997/CelebBasis/assets/24360385/10fbec8e-c623-418b-a173-5e3d4d9b7c36)

**Comment by ygtxr1997** [comment]
1. We add an example using StyleGAN3 synthetic faces, [https://github.com/ygtxr1997/CelebBasis/commit/71da8d906f0a6f91737a2713a9943dcd3d399fbe](https://github.com/ygtxr1997/CelebBasis/commit/71da8d906f0a6f91737a2713a9943dcd3d399fbe).
2. If there is only one id, the `specific ids` should be `[0]` instead of `[1]`. In `specific ids`, `1` means the  second ID, [https://github.com/ygtxr1997/CelebBasis/commit/12156a1d85691b858c4e69ee8c1fa9c30e680e95](https://github.com/ygtxr1997/CelebBasis/commit/12156a1d85691b858c4e69ee8c1fa9c30e680e95).
