### ISSUE TITLE
Missing /taming folder in the root directory (submodule needed?)

### ISSUE THREAD

**Issue by mjdi** [ygtxr1997/CelebBasis#7]
on line 6 of `/ldm/models/autoencoder.py` there is an import for a module that doesn't exist in this repo
![image](https://github.com/ygtxr1997/CelebBasis/assets/24360385/18390804-4697-48ee-9397-96a510d1d05c)

I had to git clone this repo [https://github.com/CompVis/taming-transformers/tree/master
](https://github.com/CompVis/taming-transformers/tree/master)
and copy over the /taming folder to the root directory so `autoencoder.py` would run successfully

**Comment by ygtxr1997** [comment]
We missed the requirements in `environment.yaml`. Now fixed, [https://github.com/ygtxr1997/CelebBasis/commit/bdbb5600a6ea0b56539083a7e172f8ef6b34e060](https://github.com/ygtxr1997/CelebBasis/commit/bdbb5600a6ea0b56539083a7e172f8ef6b34e060).
